### ISSUE TITLE
Where is sgfinitis ?

### ISSUE THREAD

**Issue by 123nishant** [mahmoudimus/synthetic-data-generation-framework#1]
Hi , 
I could not find a file with the name 'sgfinitis' in the repository. 

Can you please help me out here ? 

It's not working from my end.

**Comment by mahmoudimus** [comment]
Oops, sorry, that's a README.md error. It's supposed to be `sgfinit` _is_. The file is here: https://github.com/mahmoudimus/synthetic-data-generation-framework/blob/a776013a0aeab76d1a1056c6bb247c9921a78ede/source/init.cpp. Can you submit a PR with updated README?

**Comment by 123nishant** [comment]
I have created a PR for the same.

**Comment by mahmoudimus** [comment]
Fixed !
